name: Go Build and Release

on:
  push:
    branches:
      - main
      - r
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]
        include:
          - goos: linux
            goarch: amd64
          - goos: darwin
            goarch: amd64
          - goos: windows
            goarch: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go build
        run: go build -v ./...

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o hellogo-linux-amd64 .

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o hellogo-darwin-amd64 .

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o hellogo-windows-amd64.exe .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            hellogo-linux-amd64
            hellogo-darwin-amd64
            hellogo-windows-amd64.exe
